### ISSUE TITLE
Errors with installation

### ISSUE THREAD

**Issue by nllg** [DamLabResources/crseek#1]
Hello,

I am trying to install crseek in my unbuntu computer. I have followed all the steps and have installed anconda  using the command line:  wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh

Having followed the installation steps, when I enter this command line: 
conda create -yq -n crseek-environment --file requirements.conda
I get the following error:
CondaFileIOError: 'requirements.conda'. [Errno 2] No such file or directory: 'requirements.conda'

Could you please help me with this?

Thank you

**Comment by JudoWill** [comment]
Are you sure you're pointing to the right spot with your path? That line assumes the `requirements.conda` is the the same directory where you're issuing your command.
You can try being more explicit:
`conda create -yq -n crseek-environment --file /full/path/to/requirements.conda`

**Comment by nllg** [comment]
Thank  you for replying so quickly, indeed, you were right, I missed that.

Thanks again! :-)
